"""add custom_buckets table

Revision ID: 23de344fe169
Revises: 8c23b5c60843
Create Date: 2026-05-20 21:57:34.241532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23de344fe169'
down_revision: Union[str, Sequence[str], None] = '8c23b5c60843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_custom_bucket_name', 'custom_buckets', ['user_id', 'bucket_name'], unique=True)
    op.create_index('ix_custom_bucket_user', 'custom_buckets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custom_bucket_user', table_name='custom_buckets')
    op.drop_index('ix_custom_bucket_name', table_name='custom_buckets')
    op.drop_table('custom_buckets')
    # ### end Alembic commands ###
