"""add wealth_bucket to expenses

Revision ID: 3b9538e8b6c2
Revises: ce6f454fba68
Create Date: 2026-05-13 17:37:18.839192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9538e8b6c2'
down_revision: Union[str, Sequence[str], None] = 'ce6f454fba68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('wealth_bucket', sa.String(length=50), nullable=True, comment='Wealth allocation bucket: family, freedom_fund, emergency_buffer, asset_building'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'wealth_bucket')
    # ### end Alembic commands ###
