"""add bucket_activities table

Revision ID: 86f041579287
Revises: 3b9538e8b6c2
Create Date: 2026-05-18 22:29:06.658794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f041579287'
down_revision: Union[str, Sequence[str], None] = '3b9538e8b6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(length=50), nullable=False, comment='Wealth bucket: family, freedom_fund, emergency_buffer, asset_building'),
    sa.Column('activity_type', sa.Enum('allocation', 'withdrawal_transfer', 'withdrawal_expense', 'transfer_in', 'transfer_out', name='activity_type_enum', create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('related_bucket', sa.String(length=50), nullable=True, comment='For transfers: the other bucket involved'),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bucket_activity_type', 'bucket_activities', ['activity_type'], unique=False)
    op.create_index('ix_bucket_activity_user_bucket', 'bucket_activities', ['user_id', 'bucket_name'], unique=False)
    op.create_index('ix_bucket_activity_user_date', 'bucket_activities', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bucket_activity_user_date', table_name='bucket_activities')
    op.drop_index('ix_bucket_activity_user_bucket', table_name='bucket_activities')
    op.drop_index('ix_bucket_activity_type', table_name='bucket_activities')
    op.drop_table('bucket_activities')
    # ### end Alembic commands ###
