"""add committed_expenses table

Revision ID: 8c23b5c60843
Revises: 86f041579287
Create Date: 2026-05-20 10:16:09.326940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c23b5c60843'
down_revision: Union[str, Sequence[str], None] = '86f041579287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committed_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(length=20), nullable=True, comment='monthly, weekly, biweekly, yearly'),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_committed_user_due', 'committed_expenses', ['user_id', 'due_date'], unique=False)
    op.create_index('ix_committed_user_paid', 'committed_expenses', ['user_id', 'is_paid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_committed_user_paid', table_name='committed_expenses')
    op.drop_index('ix_committed_user_due', table_name='committed_expenses')
    op.drop_table('committed_expenses')
    # ### end Alembic commands ###
